package com.xmxedu.oaken.sql;

import java.util.Map;
import java.util.HashMap;
import java.sql.Connection;
import java.sql.SQLException;

import com.javaranch.jenny.prod.util.Strings;


import com.javaranch.jenny.prod.DBResults;

import com.javaranch.jenny.prod.TableFacade;


/** Strongly typed access to the database table "tb_user_ad_statistic".
 *
 * This source file was automatically generated by "Jenny the db code generator"
 * based on information found in the database.  Do not modify this file!
 *
 * For more information on Jenny, see http://www.javaranch.com/jenny.jsp
 *
 *
 * Most of the methods are static so you don't need to instantiate a copy of this class
 * to do your work.  The primary access methods are:
 * <ul>
 *
 *     <b>getRow()/getRows()/getAllRows()</b><br>
 *     <b>search()</b> <i>like getRows(), but you can specify which columns you want back</i><br>
 *     <b>update()</b><br>
 *     <b>delete()</b><br>
 *     <b>insert()</b><br>
 *
 * </ul>
 *
 * These methods all have the option of passing in a connection as the first parameter.
 * Usually you won't use a connection directly, but sometimes it's useful.
 *
 * The getRows() methods all return an array of Row objects or a single Row object.  The
 * row object is easy to work with and provides strong type checking.  If your table has
 * a lot of columns, and your search will return a lot of rows, you might want to consider
 * using a search() method instead.  You lose some of your strong type checking, but
 * you might go a lot easier on memory.  In these cases, you will want to make sure you
 * use the column name constants found at the top of this class.
 *
 */
public class TbUserAdStatisticTable
{
    private static Implementation imp = new Implementation();
    public static final String tableName = "tb_user_ad_statistic";
    public static final String idColumnName = "id";
    public static final String appidColumnName = "appid";
    public static final String adidColumnName = "adid";
    public static final String requestColumnName = "request";
    public static final String impressColumnName = "impress";
    public static final String clickColumnName = "click";
    public static final String fillrateColumnName = "fillrate";
    public static final String impressrateColumnName = "impressrate";
    public static final String clickrateColumnName = "clickrate";
    public static final String eCPMColumnName = "eCPM";
    public static final String incomeColumnName = "income";
    public static final String timeColumnName = "time";
    private static String[] allColumns =
    {
        idColumnName, appidColumnName, adidColumnName, requestColumnName, impressColumnName, clickColumnName, fillrateColumnName, impressrateColumnName, clickrateColumnName, eCPMColumnName, incomeColumnName, timeColumnName
    };

    /** You probably want to use the static methods for most of your access, but once in a while you might need to
     *  pass an instance object to a method that knows how to work with these sorts of tables.
     */
    public static Implementation getInstance()
    {
        return imp;
    }

    /** For use by unit testing, although you could provide your own implementation here if
     *  you wanted to.
     *
     *  To use this in your unit testing, create an instance of MockTbUserAdStatisticTable and pass
     *  it in here.  Then set your mock return values, call the method you are testing and examine
     *  the mock values that are now set!
     */
    public static void setInstance(TbUserAdStatisticTable.Implementation instance)
    {
        imp = instance;
    }

    /** Exposed for unit testing purposes only! */
    static class Implementation extends TableFacade
    {
        /** Exposed for unit testing purposes only! */
        Implementation()
        {
            super(SQLFacade.getInstance(), tableName);
        }

        // convert a DBResults object to an array of Row objects.
        // requires that all of the columns be represented in the DBResults object and in the right order
        private static Row[] rowArray(DBResults r)
        {
            Row[] rows = new Row[r.size()];
            for(int i = 0; i < rows.length; i++)
            {
                rows[i] = new Row(r.getRow(i));
            }
            return rows;
        }

        /** Instantiate an empty Row object */
        public Row getRow()
        {
            // if you are wondering about why this method is so lame - it's for unit testing!
            // The idea is that during unit testing, a different test object will be returned here.
            // To learn more about unit testing with Jenny generated code, visit
            // <a href="http://www.javaranch.com/jenny.jsp">www.javaranch.com/jenny.jsp</a>
            return new Row();
        }

        /** Instantiate a Row object and fill its content based on a search for the ID.
         *
         * Return null if not found.  Return first item if more than one found.
         */
        public Row getRow(Connection con, int id) throws SQLException
        {
            Row row = new Row(this.search(con, "id", String.valueOf(id), allColumns));
            return row.dataLoadedFromDatabase() ? row : null;
        }

        /** Instantiate a Row object and fill its content based on a search for the ID.
         *
         * Return null if not found.
         */
        public Row getRow(long id) throws SQLException
        {
            Row row = new Row(this.search("id", String.valueOf(id), allColumns));
            return row.dataLoadedFromDatabase() ? row : null;
        }

        /** Instantiate a Row object and fill its content based on a search
         *
         * Return null if not found.
         */
        public Row getRow(Connection con, String column, String searchText) throws SQLException
        {
            Row row = new Row(this.search(con, column, searchText, allColumns));
            return row.dataLoadedFromDatabase() ? row : null;
        }

        /** Instantiate a Row object and fill its content based on a search
         *
         * Return null if not found.
         */
        public Row getRow(String column, String searchText) throws SQLException
        {
            Row row = new Row(this.search(column, searchText, allColumns));
            return row.dataLoadedFromDatabase() ? row : null;
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows(Connection con, String column, String searchText) throws SQLException
        {
            return rowArray(this.search(con, column, searchText, allColumns));
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows(String column, String searchText) throws SQLException
        {
            return rowArray(this.search(column, searchText, allColumns));
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows(Connection con, String column, String[] searchText) throws SQLException
        {
            return rowArray(this.search(con, column, searchText, allColumns));
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows(String column, String[] searchText) throws SQLException
        {
            return rowArray(this.search(column, searchText, allColumns));
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows(Connection con, String whereClause) throws SQLException
        {
            return rowArray(this.search(con, whereClause, allColumns));
        }

        /** Return an array of length zero if nothing found */
        public Row[] getRows(String whereClause) throws SQLException
        {
            return rowArray(this.search(whereClause, allColumns));
        }


        /** Return an array of length zero if nothing found */
        public Row[] getAllRows(Connection con) throws SQLException
        {
            return rowArray(this.search(con, allColumns));
        }

        /** Return an array of length zero if nothing found */
        public Row[] getAllRows() throws SQLException
        {
            return rowArray(this.search(allColumns));
        }

        public void update(Connection con, int id, Map data) throws SQLException
        {
            this.update(con, "id", String.valueOf(id), data);
        }

        public void update(int id, Map data) throws SQLException
        {
            this.update("id", String.valueOf(id), data);
        }

        public void delete(Connection con, long id) throws SQLException
        {
            this.delete(con, "id", String.valueOf(id));
        }

        public void delete(long id) throws SQLException
        {
            this.delete("id", String.valueOf(id));
        }

        public long insertAndGetID(Connection con, Map data) throws SQLException
        {
            return this.insertAndGetID(con, data, "id");
        }

        public long insertAndGetID(Map data) throws SQLException
        {
            return this.insertAndGetID(data, "id");
        }

    }
    public static class Row
    {
        private boolean dataLoadedFromDatabase = false;

        private int id;
        private String appid;
        private int adid;
        private int request;
        private boolean requestNull = true;
        private int impress;
        private boolean impressNull = true;
        private int click;
        private boolean clickNull = true;
        private double fillrate;
        private boolean fillrateNull = true;
        private double impressrate;
        private boolean impressrateNull = true;
        private double clickrate;
        private boolean clickrateNull = true;
        private double eCPM;
        private boolean eCPMNull = true;
        private double income;
        private boolean incomeNull = true;
        private int time;

        /** for internal use only!   If you need a row object, use getRow(). */
        Row()
        {
        }

        private Row(String[] data)
        {
            if (data != null)
            {
                this.id = Integer.parseInt(data[0]);
                this.appid = data[1];
                this.adid = Integer.parseInt(data[2]);
                this.requestNull = (data[3] == null);
                this.request = requestNull ? 0 : Integer.parseInt(data[3]);
                this.impressNull = (data[4] == null);
                this.impress = impressNull ? 0 : Integer.parseInt(data[4]);
                this.clickNull = (data[5] == null);
                this.click = clickNull ? 0 : Integer.parseInt(data[5]);
                this.fillrateNull = (data[6] == null);
                this.fillrate = fillrateNull ? 0.0 : Double.parseDouble(data[6]);
                this.impressrateNull = (data[7] == null);
                this.impressrate = impressrateNull ? 0.0 : Double.parseDouble(data[7]);
                this.clickrateNull = (data[8] == null);
                this.clickrate = clickrateNull ? 0.0 : Double.parseDouble(data[8]);
                this.eCPMNull = (data[9] == null);
                this.eCPM = eCPMNull ? 0.0 : Double.parseDouble(data[9]);
                this.incomeNull = (data[10] == null);
                this.income = incomeNull ? 0.0 : Double.parseDouble(data[10]);
                this.time = Integer.parseInt(data[11]);
                dataLoadedFromDatabase = true;
            }
        }

        private Row(DBResults results)
        {
            this(results.getRow(0));
        }
        public int getID()
        {
            return id;
        }

        public void setID(int id)
        {
            this.id = id;
        }


        public String getAppid()
        {
            return appid;
        }

        public void setAppid(String appid)
        {
            this.appid = appid;
        }


        public int getAdid()
        {
            return adid;
        }

        public void setAdid(int adid)
        {
            this.adid = adid;
        }


        public int getRequest()
        {
            return request;
        }

        public void setRequest(int request)
        {
            this.request = request;
            requestNull = false;
        }

        public void setRequest(Integer request)
        {
            requestNull = (request == null);
            if (requestNull)
            {
                this.request = 0;
            }
            else
            {
                this.request = request.intValue();
            }
        }

        public boolean isRequestNull()
        {
            return requestNull;
        }

        public void setRequestNull(boolean requestNull)
        {
            this.requestNull = requestNull;
            if (requestNull)
            {
                request = 0;
            }
        }


        public int getImpress()
        {
            return impress;
        }

        public void setImpress(int impress)
        {
            this.impress = impress;
            impressNull = false;
        }

        public void setImpress(Integer impress)
        {
            impressNull = (impress == null);
            if (impressNull)
            {
                this.impress = 0;
            }
            else
            {
                this.impress = impress.intValue();
            }
        }

        public boolean isImpressNull()
        {
            return impressNull;
        }

        public void setImpressNull(boolean impressNull)
        {
            this.impressNull = impressNull;
            if (impressNull)
            {
                impress = 0;
            }
        }


        public int getClick()
        {
            return click;
        }

        public void setClick(int click)
        {
            this.click = click;
            clickNull = false;
        }

        public void setClick(Integer click)
        {
            clickNull = (click == null);
            if (clickNull)
            {
                this.click = 0;
            }
            else
            {
                this.click = click.intValue();
            }
        }

        public boolean isClickNull()
        {
            return clickNull;
        }

        public void setClickNull(boolean clickNull)
        {
            this.clickNull = clickNull;
            if (clickNull)
            {
                click = 0;
            }
        }


        public double getFillrate()
        {
            return fillrate;
        }

        public void setFillrate(double fillrate)
        {
            this.fillrate = fillrate;
            fillrateNull = false;
        }

        public void setFillrate(Double fillrate)
        {
            fillrateNull = (fillrate == null);
            if (fillrateNull)
            {
                this.fillrate = 0.0;
            }
            else
            {
                this.fillrate = fillrate.doubleValue();
            }
        }

        public boolean isFillrateNull()
        {
            return fillrateNull;
        }

        public void setFillrateNull(boolean fillrateNull)
        {
            this.fillrateNull = fillrateNull;
            if (fillrateNull)
            {
                fillrate = 0.0;
            }
        }


        public double getImpressrate()
        {
            return impressrate;
        }

        public void setImpressrate(double impressrate)
        {
            this.impressrate = impressrate;
            impressrateNull = false;
        }

        public void setImpressrate(Double impressrate)
        {
            impressrateNull = (impressrate == null);
            if (impressrateNull)
            {
                this.impressrate = 0.0;
            }
            else
            {
                this.impressrate = impressrate.doubleValue();
            }
        }

        public boolean isImpressrateNull()
        {
            return impressrateNull;
        }

        public void setImpressrateNull(boolean impressrateNull)
        {
            this.impressrateNull = impressrateNull;
            if (impressrateNull)
            {
                impressrate = 0.0;
            }
        }


        public double getClickrate()
        {
            return clickrate;
        }

        public void setClickrate(double clickrate)
        {
            this.clickrate = clickrate;
            clickrateNull = false;
        }

        public void setClickrate(Double clickrate)
        {
            clickrateNull = (clickrate == null);
            if (clickrateNull)
            {
                this.clickrate = 0.0;
            }
            else
            {
                this.clickrate = clickrate.doubleValue();
            }
        }

        public boolean isClickrateNull()
        {
            return clickrateNull;
        }

        public void setClickrateNull(boolean clickrateNull)
        {
            this.clickrateNull = clickrateNull;
            if (clickrateNull)
            {
                clickrate = 0.0;
            }
        }


        public double getECPM()
        {
            return eCPM;
        }

        public void setECPM(double eCPM)
        {
            this.eCPM = eCPM;
            eCPMNull = false;
        }

        public void setECPM(Double eCPM)
        {
            eCPMNull = (eCPM == null);
            if (eCPMNull)
            {
                this.eCPM = 0.0;
            }
            else
            {
                this.eCPM = eCPM.doubleValue();
            }
        }

        public boolean isECPMNull()
        {
            return eCPMNull;
        }

        public void setECPMNull(boolean eCPMNull)
        {
            this.eCPMNull = eCPMNull;
            if (eCPMNull)
            {
                eCPM = 0.0;
            }
        }


        public double getIncome()
        {
            return income;
        }

        public void setIncome(double income)
        {
            this.income = income;
            incomeNull = false;
        }

        public void setIncome(Double income)
        {
            incomeNull = (income == null);
            if (incomeNull)
            {
                this.income = 0.0;
            }
            else
            {
                this.income = income.doubleValue();
            }
        }

        public boolean isIncomeNull()
        {
            return incomeNull;
        }

        public void setIncomeNull(boolean incomeNull)
        {
            this.incomeNull = incomeNull;
            if (incomeNull)
            {
                income = 0.0;
            }
        }


        public int getTime()
        {
            return time;
        }

        public void setTime(int time)
        {
            this.time = time;
        }


        private boolean dataLoadedFromDatabase()
        {
            return dataLoadedFromDatabase;
        }
        private Map buildDataMap()
        {
            Map data = new HashMap();
            data.put(idColumnName, String.valueOf(this.id));
            data.put(appidColumnName, this.appid);
            data.put(adidColumnName, String.valueOf(this.adid));
            data.put(requestColumnName, this.requestNull ? null : String.valueOf(this.request));
            data.put(impressColumnName, this.impressNull ? null : String.valueOf(this.impress));
            data.put(clickColumnName, this.clickNull ? null : String.valueOf(this.click));
            data.put(fillrateColumnName, this.fillrateNull ? null : String.valueOf(this.fillrate));
            data.put(impressrateColumnName, this.impressrateNull ? null : String.valueOf(this.impressrate));
            data.put(clickrateColumnName, this.clickrateNull ? null : String.valueOf(this.clickrate));
            data.put(eCPMColumnName, this.eCPMNull ? null : String.valueOf(this.eCPM));
            data.put(incomeColumnName, this.incomeNull ? null : String.valueOf(this.income));
            data.put(timeColumnName, String.valueOf(this.time));
            return data;
        }

        /** update a row object based on a search */
        public void update(Connection con, String column, String searchText) throws SQLException
        {
            imp.update(con, column, searchText, buildDataMap());
        }

        /** update a row object based on a search */
        public void update(String column, String searchText) throws SQLException
        {
            imp.update(column, searchText, buildDataMap());
        }

        /** update a row object based on the id */
        public void update(Connection con) throws SQLException
        {
            imp.update(con, id, buildDataMap());
        }

        /** update a row object based on the id */
        public void update() throws SQLException
        {
            imp.update(id, buildDataMap());
        }

        /** create a new row complete with a new ID.
            The current ID is ignored.  The new ID is placed in the row.
            @return the new row ID
        */
        public long insert(Connection con) throws SQLException
        {
            return imp.insertAndGetID(con, buildDataMap());
        }

        /** create a new row complete with a new ID.
            The current ID is ignored.  The new ID is placed in the row.
            @return the new row ID
        */
        public long insert() throws SQLException
        {
            return imp.insertAndGetID(buildDataMap());
        }

        /** delete a row object based on the id */
        public void delete(Connection con) throws SQLException
        {
            imp.delete(con, id);
        }

        /** delete a row object based on the id */
        public void delete() throws SQLException
        {
            imp.delete(id);
        }

    }

    /** Return an empty row object */
    public static Row getRow()
    {
        return imp.getRow();
    }

    /** Instantiate a Row object and fill its content based on a search for the ID.
     *
     * Return null if not found.
     */

    public static Row getRow(Connection con, int id) throws SQLException
    {
        return imp.getRow(con, id);
    }

    /** Instantiate a Row object and fill its content based on a search for the ID.
     *
     * Return null if not found.
     */
    public static Row getRow(long id) throws SQLException
    {
        return imp.getRow(id);
    }

    /** Instantiate a Row object and fill its content based on a search
     *
     * Return null if not found.
     */
    public static Row getRow(Connection con, String column, String searchText) throws SQLException
    {
        return imp.getRow(con, column, searchText);
    }

    /** Instantiate a Row object and fill its content based on a search
     *
     * Return null if not found.
     */
    public static Row getRow(String column, String searchText) throws SQLException
    {
        return imp.getRow(column, searchText);
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(Connection con, String column, String searchText) throws SQLException
    {
        return imp.getRows(con, column, searchText);
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(String column, String searchText) throws SQLException
    {
        return imp.getRows(column, searchText);
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(Connection con, String column, String[] searchText) throws SQLException
    {
        return imp.getRows(con, column, searchText);
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(String column, String[] searchText) throws SQLException
    {
        return imp.getRows(column, searchText);
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(Connection con, String column, int searchValue) throws SQLException
    {
        return imp.getRows(con, column, String.valueOf(searchValue));
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(String column, int searchValue) throws SQLException
    {
        return imp.getRows(column, String.valueOf(searchValue));
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(Connection con, String column, int[] searchValues) throws SQLException
    {
        return imp.getRows(con, column, Strings.toStringArray(searchValues));
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(String column, int[] searchValues) throws SQLException
    {
        return imp.getRows(column, Strings.toStringArray(searchValues));
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(Connection con, String whereClause) throws SQLException
    {
        return imp.getRows(con, whereClause);
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getRows(String whereClause) throws SQLException
    {
        return imp.getRows(whereClause);
    }


    /** Return an array of length zero if nothing found */
    public static Row[] getAllRows(Connection con) throws SQLException
    {
        return imp.getAllRows(con);
    }

    /** Return an array of length zero if nothing found */
    public static Row[] getAllRows() throws SQLException
    {
        return imp.getAllRows();
    }

    public static DBResults search(Connection con, String column, String searchText, String[] dataColumns) throws SQLException
    {
        return imp.search(con, column, searchText, dataColumns);
    }

    public static DBResults search(String column, String searchText, String[] dataColumns) throws SQLException
    {
        return imp.search(column, searchText, dataColumns);
    }

    public static DBResults search(Connection con, String column, String[] searchText, String[] dataColumns) throws SQLException
    {
        return imp.search(con, column, searchText, dataColumns);
    }

    public static DBResults search(String column, String searchText[], String[] dataColumns) throws SQLException
    {
        return imp.search(column, searchText, dataColumns);
    }

    public static DBResults search(Connection con, String column, int searchValue, String[] dataColumns) throws SQLException
    {
        return imp.search(con, column, searchValue, dataColumns);
    }

    public static DBResults search(String column, int searchValue, String[] dataColumns) throws SQLException
    {
        return imp.search(column, searchValue, dataColumns);
    }

    public static DBResults search(Connection con, String column, int[] searchValues, String[] dataColumns) throws SQLException
    {
        return imp.search(con, column, searchValues, dataColumns);
    }

    public static DBResults search(String column, int[] searchValues, String[] dataColumns) throws SQLException
    {
        return imp.search(column, searchValues, dataColumns);
    }

    public static DBResults search(Connection con, String whereClause, String[] dataColumns) throws SQLException
    {
        return imp.search(con, whereClause, dataColumns);
    }

    public static DBResults search(String whereClause, String[] dataColumns) throws SQLException
    {
        return imp.search(whereClause, dataColumns);
    }

    public static DBResults search(Connection con, String[] dataColumns) throws SQLException
    {
        return imp.search(con, dataColumns);
    }

    public static DBResults search(String[] dataColumns) throws SQLException
    {
        return imp.search(dataColumns);
    }

    public static void update(Connection con, String column, String searchText, Map data) throws SQLException
    {
        imp.update(con, column, searchText, data);
    }

    public static void update(String column, String searchText, Map data) throws SQLException
    {
        imp.update(column, searchText, data);
    }

    public static void delete(Connection con, long id) throws SQLException
    {
        imp.delete(con, id);
    }

    public static void delete(long id) throws SQLException
    {
        imp.delete(id);
    }

    public static void delete(Connection con, String column, String searchText) throws SQLException
    {
        imp.delete(con, column, searchText);
    }

    public static void delete(String column, String searchText) throws SQLException
    {
        imp.delete(column, searchText);
    }

    public static long insert(Connection con, Map data) throws SQLException
    {
        return imp.insertAndGetID(con, data);
    }

    public static long insert(Map data) throws SQLException
    {
        return imp.insertAndGetID(data);
    }

}

